 ## 处理重复数据

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_obj = pd.DataFrame({'data1' : ['a'] * 4 + ['b'] * 4,
                       'data2' : np.random.randint(0, 4, 8)})
print(df_obj)

  data1  data2
0     a      0
1     a      2
2     a      1
3     a      2
4     b      2
5     b      0
6     b      2
7     b      2

In [3]:
print(df_obj.duplicated())

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
dtype: bool

In [4]:
df_obj[~df_obj.duplicated()]  #取出不重复行

  data1  data2
0     a      0
1     a      2
2     a      1
4     b      2
5     b      0

In [5]:
#按照某一列去重
print(df_obj.duplicated('data2'))

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7     True
dtype: bool

In [6]:
df_obj1 = pd.DataFrame({'data1' :[np.nan] * 4,
                       'data2' :list('1235')})
df_obj1

   data1 data2
0    NaN     1
1    NaN     2
2    NaN     3
3    NaN     5

In [7]:
#在pd的duplicated认为空值和空值相等的
df_obj1.duplicated('data1')
print(df_obj1.drop_duplicates('data1'))

   data1 data2
0    NaN     1

In [8]:
print(df_obj.drop_duplicates())  #删除重复行
print(df_obj.drop_duplicates('data2'))

  data1  data2
0     a      0
1     a      2
2     a      1
4     b      2
5     b      0
  data1  data2
0     a      0
1     a      2
2     a      1

In [9]:
#如果要在原有的df上去重，需要加inplace=True
df_obj

  data1  data2
0     a      0
1     a      2
2     a      1
3     a      2
4     b      2
5     b      0
6     b      2
7     b      2

In [10]:
#map与applymap一样，但是map只能用于series，applymap只能用于df
ser_obj = pd.Series(np.random.randint(0,10,10))  #series 用map
print(ser_obj)

print(ser_obj.map(lambda x : x ** 2))

0    4
1    4
2    2
3    4
4    6
5    4
6    5
7    0
8    8
9    5
dtype: int32
0    16
1    16
2     4
3    16
4    36
5    16
6    25
7     0
8    64
9    25
dtype: int64

In [11]:
#异常值手动替换
ser_obj=pd.Series(np.arange(10),index=range(3,13))
# 单个值替换单个值
print(ser_obj.replace(1, -100))
print('-' * 20)
# 多个值替换一个值
print(ser_obj.replace(range(6,9), -100))
print('-' * 20)
# 多个值替换多个值
print(ser_obj.replace([4, 7], [-100, -200]))

3       0
4    -100
5       2
6       3
7       4
8       5
9       6
10      7
11      8
12      9
dtype: int32
--------------------
3       0
4       1
5       2
6       3
7       4
8       5
9    -100
10   -100
11   -100
12      9
dtype: int32
--------------------
3       0
4       1
5       2
6       3
7    -100
8       5
9       6
10   -200
11      8
12      9
dtype: int32

In [12]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9],
                   'C': ['a', 'b', 'ac', 'd', 'e']})

In [13]:
df

   A  B   C
0  0  5   a
1  1  6   b
2  2  7  ac
3  3  8   d
4  4  9   e

In [14]:
#正则表达式替换
df.replace(to_replace=r'^a', value=100, regex=True)

   A  B    C
0  0  5  100
1  1  6    b
2  2  7  100
3  3  8    d
4  4  9    e

In [15]:
df.dtypes

A     int64
B     int64
C    object
dtype: object